{% set version = "3.11.0" %}

package:
  name: flit-core
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/flit/flit-{{ version }}.tar.gz
  sha256: 58d0a07f684c315700c9c54a661a1130995798c3e495db0db53ce6e7d0121825
  folder: source

build:
  script: python -m pip install --no-deps -vv source/flit_core/
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
  run_constrained:
    - flit {{ version }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - flit_core
    - flit_core.common

about:
  home: https://flit.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: source/LICENSE
  summary: Simplified packaging of Python modules

extra:
  recipe-maintainers:
    - takluyver
    - beckermr
