{% set version = "3.10.0" %}

package:
  name: flit-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flit/flit-{{ version }}.tar.gz
  sha256: dadca58d5097db62884d25d70b572f104954927daadc8cee449739215b7237fd
  folder: source

build:
  script: python -m pip install --no-deps -vv source/flit_core/
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
  run_constrained:
    - flit {{ version }}

test:
  imports:
    - flit_core
    - flit_core.common

about:
  home: https://flit.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: source/LICENSE
  summary: Simplified packaging of Python modules

extra:
  recipe-maintainers:
    - takluyver
    - beckermr
