{% set version = "3.10.1" %}

package:
  name: flit-core
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/flit/flit-{{ version }}.tar.gz
  sha256: 9c6258ae76d218ce60f9e39a43ca42006a3abcc5c44ea6bb2a1daa13857a8f1a
  folder: source

build:
  script: python -m pip install --no-deps -vv source/flit_core/
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
  run_constrained:
    - flit {{ version }}

test:
  imports:
    - flit_core
    - flit_core.common

about:
  home: https://flit.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: source/LICENSE
  summary: Simplified packaging of Python modules

extra:
  recipe-maintainers:
    - takluyver
    - beckermr
